[[language]]
name = 'nim'
scope = 'source.nim'
injection-regex = 'nim'
file-types = ['nim','nims']
shebangs = ['nim']
roots = []
comment-token = '#'
language-server = { command = 'nimlsp' }
indent = { tab-width = 2, unit = ' ' }

[[grammar]]
name = 'nim'
source = { git = 'https://github.com/aMOPel/tree-sitter-nim', rev = '8ce3627827e45a5835004391ff5ffcfe029ae6cf' }


[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py","pyi","py3","pyw","ptl",".pythonstartup",".pythonrc","SConstruct"]
shebangs = ["python"]
roots = []
comment-token = "#"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {}
formatter = { command = "pyfmt" }
auto-format = true
indent = { tab-width = 4, unit = "    " }